
[[_jdiameter_configuration]]
= Diameter Stack Configuration

The stack is initially configured by parsing an XML file.
The top level structure of the file is described below.
Further explanation of each child element, and the applicable attributes, is provided later in this section.

[source,xml]
----
<Configuration xmlns="http://www.jdiameter.org/jdiameter-server">

	<LocalPeer></LocalPeer>
	<Parameters></Parameters>
	<Network></Network>
	<Extensions></Extensions>

</Configuration>
----

[source,xml]
----
<LocalPeer>
	<URI value="aaa://localhost:3868"/>
	<IPAddresses>
		<IPAddress value="127.0.0.1"/>
	</IPAddresses>

	<Realm value="mobicents.org"/>
	<VendorID value="193"/>
	<ProductName value="jDiameter"/>
	<FirmwareRevision value="1"/>

	<OverloadMonitor>
		<Entry index="1" lowThreshold="0.5" highThreshold="0.6">
			<ApplicationID>
				<VendorId value="193"/>
				<AuthApplId value="0"/>
				<AcctApplId value="19302"/>
			</ApplicationID>
		</Entry>
	</OverloadMonitor>
	<Applications>
		<ApplicationID>
			<VendorId value="193"/>
			<AuthApplId value="0"/>
			<AcctApplId value="19302"/>
		</ApplicationID>
	</Applications>
</LocalPeer>
----

The <LocalPeer> element contains parameters that affect the local Diameter peer.
The available elements and attributes are listed for reference.

.<LocalPeer> Elements and Attributes
<URI>::
  Specifies the URI for the local peer.
  The URI has the following format: "aaa://FQDN:port".

<IPAddresses>::
  Contains one or more child <IPAddress> element, which contain a single, valid IP address for the local peer, stored in the [parameter]`value` attribute of the IPAddress.

<Realm>::
  Specifies the realm of the local peer, using the [parameter]`value` attribute.

<VendorID>::
  Specifies a numeric identifier that corresponds to the vendor ID allocated by IANA. 

<ProductName>::
  Specifies the name of the local peer product.

<FirmwareRevision>::
  Specifies the version of the firmware.

<OverloadMonitor>::
  Optional parent element containing child elements that specify settings relating to the Overload Monitor.

<Entry>::
  Supports <ApplicationID> child elements that specify the ID of the tracked application(s). It also supports the following properties: 

index
  Defines the index of this overload monitor, so priorities/orders can be specified.

lowThreshold
  The low threshold for activation of the overload monitor.

highThreshold
  The high threshold for activation of the overload monitor.

<ApplicationID>::
  Parent element containing child elements that specify information about the application.
  The child elements create a unique application identifier.
  The child elements are:

<VendorId>
Specifies the vendor ID for application definition. It supports a single property: "value".

<AuthAppId>
The Authentication Application ID for application definition. It supports a single property: "value".

<AcctAplId>
The Account Application ID for application definition. It supports a single property: "value".

<Applications>::
  Contains a child element <ApplicationID>, which defines the list of default supported applications.
  It is used for the server side, when the stack is configured to accept incoming calls and there is an empty list of preconfigured peers (server is configured to accept any connection).

[source,xml]
----
<Parameters>

	<AcceptUndefinedPeer value="true"/>
	<DuplicateProtection value="true"/>
  <DuplicateTimer value="240000"/>
  <DuplicateSize value="5000"/>
	<UseUriAsFqdn value="true"/> <!-- Needed for Ericsson SDK Emulator -->
	<QueueSize value="10000"/>
	<MessageTimeOut value="60000"/>
	<StopTimeOut value="10000"/>
	<CeaTimeOut value="10000"/>
	<IacTimeOut value="30000"/>
	<DwaTimeOut value="10000"/>
	<DpaTimeOut value="5000"/>
	<RecTimeOut value="10000"/>

	<!-- Peer FSM Thread Count Configuration -->
	<PeerFSMThreadCount value="3" />

	<Concurrent>
		<Entity name="ThreadGroup" size="64"/>
		<Entity name="ProcessingMessageTimer" size="1"/>
		<Entity name="DuplicationMessageTimer" size="1"/>
		<Entity name="RedirectMessageTimer" size="1"/>
		<Entity name="PeerOverloadTimer" size="1"/>
		<Entity name="ConnectionTimer" size="1"/>
		<Entity name="StatisticTimer" size="1"/>
		<Entity name="ApplicationSession" size="16"/>
	</Concurrent>

</Parameters>
----

The <Parameters> element contains elements that specify parameters for the Diameter stack.
The available elements and attributes are listed for reference.
If not specified otherwise, each tag supports a single property - "value", which indicates the value of the tag.

.<Parameters> Elements and Attributes
<AcceptUndefinedPeer>::
  Specifies whether the stack will accept connections from undefined peers.
  The default value is `false`.

<DuplicateProtection>::
  Specifies whether duplicate message protection is enabled.
  The default value is `false`.

<DuplicateTimer>::
  Specifies the time each duplicate message is valid for (in extreme cases, it can live up to 2 * DuplicateTimer - 1 milliseconds). The default, minimum value is `240000` (4 minutes in milliseconds).

<DuplicateSize>::
  Specifies the number of requests stored for duplicate protection.
  The default value is `5000`.

<UseUriAsFqdn>::
  Determines whether the URI should be used as FQDN.
  If it is set to `true`, the stack expects the destination/origin host to be in the format of "aaa://isdn.domain.com:3868" rather than the normal "isdn.domain.com". The default value is `false`.

<QueueSize>::
  Determines how many tasks the peer state machine can have before rejecting the next task.
  This queue contains FSM events and messaging.

<MessageTimeOut>::
  Determines the timeout for messages other than protocol FSM messages.
  The delay is in milliseconds.

<StopTimeOut>::
  Determines how long the stack waits for all resources to stop.
  The delays are in milliseconds.

<CeaTimeOut>::
  Determines how long it takes for CER/CEA exchanges to timeout if there is no response.
  The delays are in milliseconds.

<IacTimeOut>::
  Determines how long the stack waits to retry the communication with a peer that has stopped answering DWR messages.
  The delay is in milliseconds.

<DwaTimeOut>::
  Determines how long it takes for a DWR/DWA exchange to timeout if there is no response.
  The delay is in milliseconds.

<DpaTimeOut>::
  Determines how long it takes for a DPR/DPA exchange to timeout if there is no response.
  The delay is in milliseconds.

<RecTimeOut>::
  Determines how long it takes for the reconnection procedure to timeout.
  The delay is in milliseconds.

<PeerFSMThreadCount>::
  Determines the number of threads for handling events in the Peer FSM.

<Concurrent />::
  Controls the thread pool sizes for different aspects of the stack.
  It supports multiple [parameter]`Entity` child elements. [parameter]`Entity` elements configure thread groups.
  These elements support the following properties:

name
Specifies the name of the entity.

size
Specifies the thread pool size of the entity.

The default supported entities are:

ThreadGroup
Determines the maximum thread count in other entities.

ProcessingMessageTimer
Determines the thread count for message processing tasks.

DuplicationMessageTimer
Specifies the thread pool for identifying duplicate messages.

RedirectMessageTimer
Specifies the thread pool for redirecting messages that do not need any further processing.

PeerOverloadTimer
Determines the thread pool for managing the overload monitor.

ConnectionTimer
Determines the thread pool for managing tasks regarding peer connection FSM.

StatisticTimer
Determines the thread pool for statistic gathering tasks.

ApplicationSession
Determines the thread pool for managing the invocation of application session FSMs, which will invoke listeners.

[source,xml]
----
<Network>

	<Peers>
		<!-- This peer is a server, if it's a client attempt_connect should be set to false -->
		<Peer name="aaa://127.0.0.1:3868" attempt_connect="true" rating="1"/>
	</Peers>

	<Realms>
		<Realm name="mobicents.org" peers="127.0.0.1" local_action="LOCAL" dynamic="false" exp_time="1">
			<ApplicationID>
				<VendorId value="193"/>
				<AuthApplId value="0"/>
				<AcctApplId value="19302"/>
			</ApplicationID>
		</Realm>
	</Realms>

</Network>
----

The <Network> element contains elements that specify parameters for external peers.
The available elements and attributes are listed for reference.

.<Network> Elements and Attributes
<Peers>::
  Parent element containing the child element <Peer>, which specifies external peers and the way they connect.
  <Peer> specifies the name of external peers, whether they should be treated as a server or client, and what rating the peer has externally.

<Peer> supports the following properties:

name
Specifies the name of the peer in the form of a URI. The structure is "aaa://[fqdn|ip]:port" (for example, "aaa://192.168.1.1:3868").

attempt_connect
Determines if the stack should try to connect to this peer. This property accepts boolean values.

rating
Specifies the rating of this peer in order to achieve peer priorities/sorting.

<Realms>::
  Parent element containing the child element <Realm>, which specifies all realms that connect into the Diameter network.
  <Realm> contains attributes and elements that describe different realms configured for the Core.
  It supports <ApplicationID> child elements, which define the applications supported.

<Realm> supports the following parameters:

peers
Comma separated list of peers. Each peer is represented by an IP Address or FQDN.

local_action
Determines the action the Local Peer will play on the specified realm: Act as a LOCAL peer.

dynamic
Specifies if this realm is dynamic. That is, peers that connect to peers with this realm name will be added to the realm peer list if not present already.

exp_time
The time before a peer belonging to this realm is removed if no connection is available.


Below is an example configuration file for a server supporting the CCA, Sh and Ro Applications:

[source,xml]
----
<?xml version="1.0"?>
<Configuration xmlns="http://www.jdiameter.org/jdiameter-server">

	<LocalPeer>
		<URI value="aaa://127.0.0.1:3868" />
		<Realm value="mobicents.org" />
		<VendorID value="193" />
		<ProductName value="jDiameter" />
		<FirmwareRevision value="1" />
		<OverloadMonitor>
			<Entry index="1" lowThreshold="0.5" highThreshold="0.6">
				<ApplicationID>
					<VendorId value="193" />
					<AuthApplId value="0" />
					<AcctApplId value="19302" />
				</ApplicationID>
			</Entry>
		</OverloadMonitor>
	</LocalPeer>

	<Parameters>
		<AcceptUndefinedPeer value="true" />
		<DuplicateProtection value="true" />
    <DuplicateTimer value="240000" />
    <DuplicateSize value="5000" />
		<UseUriAsFqdn value="false" /> <!-- Needed for Ericsson Emulator (set to true) -->
		<QueueSize value="10000" />
		<MessageTimeOut value="60000" />
		<StopTimeOut value="10000" />
		<CeaTimeOut value="10000" />
		<IacTimeOut value="30000" />
		<DwaTimeOut value="10000" />
		<DpaTimeOut value="5000" />
		<RecTimeOut value="10000" />

		<PeerFSMThreadCount value="3" />

		<Concurrent>
			 <Entity name="ThreadGroup" size="64"/>
			 <Entity name="ProcessingMessageTimer" size="1"/>
			 <Entity name="DuplicationMessageTimer" size="1"/>
			 <Entity name="RedirectMessageTimer" size="1"/>
			 <Entity name="PeerOverloadTimer" size="1"/>
			 <Entity name="ConnectionTimer" size="1"/>
			 <Entity name="StatisticTimer" size="1"/>
			 <Entity name="ApplicationSession" size="16"/>
		</Concurrent>
	</Parameters>

	<Network>
		<Peers>
			<Peer name="aaa://127.0.0.1:1218" attempt_connect="false" rating="1" />
		</Peers>
		<Realms>
			<!-- CCA -->
			<Realm name="mobicents.org" peers="127.0.0.1" local_action="LOCAL" 
				dynamic="false" exp_time="1">
				<ApplicationID>
					<VendorId value="0" />
					<AuthApplId value="4" />
					<AcctApplId value="0" />
				</ApplicationID>
			</Realm>
			
			<!-- Sh -->
			<Realm name="mobicents.org" peers="127.0.0.1" local_action="LOCAL" 
				dynamic="false" exp_time="1">
				<ApplicationID>
					<VendorId value="10415" />
					<AuthApplId value="16777217" />
					<AcctApplId value="0" />
				</ApplicationID>
			</Realm>

			<!-- Ro -->
			<Realm name="mobicents.org" peers="127.0.0.1" local_action="LOCAL" 
				dynamic="false" exp_time="1">
				<ApplicationID>
					<VendorId value="10415" />
					<AuthApplId value="4" />
					<AcctApplId value="0" />
				</ApplicationID>
			</Realm>
		</Realms>
	</Network>

	<Extensions />

</Configuration>
----

[[_jdiameter_cluster_configuration]]
== Cluster configuration

The following list defines the requirements for enabling stack cluster mode

* Add the following entries to the `Parameters` section of [path]_jdiameter-config.xml_: 
+
[source,xml]
----

				
<SessionDatasource>org.mobicents.diameter.impl. ha.data.ReplicatedData</SessionDatasource>
<TimerFacility>org.mobicents.diameter.impl.ha. timer.ReplicatedTimerFacilityImpl</TimerFacility>
----

* A proper `JBoss Cache` configuration file: [path]_jdiameter-jbc.xml_ (located in the [path]_config_ directory).
+
The following content is sufficient for the JBoss Cache configuration file: 
+
[source,xml]
----

				
<?xml version="1.0" encoding="UTF-8"?>

<jbosscache xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="urn:jboss:jbosscache-core:config:3.0">

	<locking isolationLevel="REPEATABLE_READ"
		lockParentForChildInsertRemove="false" lockAcquisitionTimeout="20000"
		nodeLockingScheme="mvcc" writeSkewCheck="false" concurrencyLevel="500" />

	<jmxStatistics enabled="false" />

	<startup regionsInactiveOnStartup="false" />
	<shutdown hookBehavior="DEFAULT" />
	<listeners asyncPoolSize="1" asyncQueueSize="100000" />

	<invocationBatching enabled="false" />

	<serialization objectInputStreamPoolSize="12"
		objectOutputStreamPoolSize="14" version="3.0.0"
		marshallerClass="org.jboss.cache.marshall.CacheMarshaller300"
		useLazyDeserialization="false" useRegionBasedMarshalling="false" />

	<clustering mode="replication" clusterName="DiameterCluster">

		<async useReplQueue="true" replQueueInterval="1000"
			replQueueMaxElements="500" serializationExecutorPoolSize="20"
			serializationExecutorQueueSize="5000000"/>

		<jgroupsConfig>
			<UDP
				mcast_addr="${jgroups.udp.mcast_addr:228.10.10.10}"
				mcast_port="${jgroups.udp.mcast_port:18811}"
				discard_incompatible_packets="true"
				max_bundle_size="60000"
				max_bundle_timeout="30"
				ip_ttl="${jgroups.udp.ip_ttl:2}"
				enable_bundling="true"
				thread_pool.enabled="true"
				thread_pool.min_threads="1"
				thread_pool.max_threads="25"
				thread_pool.keep_alive_time="5000"
				thread_pool.queue_enabled="false"
				thread_pool.queue_max_size="100"
				thread_pool.rejection_policy="Run"
				oob_thread_pool.enabled="true"
				oob_thread_pool.min_threads="1"
				oob_thread_pool.max_threads="8"
				oob_thread_pool.keep_alive_time="5000"
				oob_thread_pool.queue_enabled="false"
				oob_thread_pool.queue_max_size="100"
				oob_thread_pool.rejection_policy="Run"/>

			<PING timeout="2000"
				num_initial_members="3"/>
			<MERGE2 max_interval="30000"
				min_interval="10000"/>
			<FD_SOCK/>
			<FD timeout="10000" max_tries="5" />
			<VERIFY_SUSPECT timeout="1500"  />
			<BARRIER />
			<pbcast.NAKACK
				use_mcast_xmit="false" gc_lag="0"
				retransmit_timeout="300,600,1200,2400,4800"
				discard_delivered_msgs="true"/>
			<UNICAST timeout="300,600,1200,2400,3600"/>
			<pbcast.STABLE stability_delay="1000" desired_avg_gossip="50000"
				max_bytes="400000"/>
			<VIEW_SYNC avg_send_interval="60000"   />
			<pbcast.GMS print_local_addr="true" join_timeout="3000"
				view_bundling="true"/>
			<FC max_credits="20000000"
				min_threshold="0.10"/>
			<FRAG2 frag_size="60000"  />
			<pbcast.STATE_TRANSFER  />
		</jgroupsConfig>
	</clustering>

</jbosscache>
----
